// const request = require('supertest')
// const app = require('../../server')
// const uniqueId = 123;

// describe('Post Endpoints', () => {

//   it('should create a new book post', async () => {
//     const res = await request(app)
//       .post('/api/books')
//       .send({
//         "id": `${uniqueId}`,
//         "name": "Harry Potter And The Philosopher`s Stone",
//         "authors": "J.K Rowling"
//       });
//     expect(res.statusCode).toEqual(200);
//     expect(res.body).toHaveProperty('updatedAt');
//   });

//   it('should create a new ebook post', async () => {
//     const res = await request(app)
//       .post('/api/eBooks')
//       .send({
//         "id": `${uniqueId}`,
//         "name": "Harry Potter And The Philosopher`s Stone",
//         "authors": "J.K Rowling",
//         "format": "PDF"
//       });
//     expect(res.statusCode).toEqual(200);
//     expect(res.body).toHaveProperty('updatedAt');
//   });


  // it('should update a post', async () => {
  //   const res = await request(app)
  //     .put('/api/books')
  //     .send({
  //       "id": `${uniqueId}`,
  //       "name": "Harry Potter And The Philosopher`s Stone",
  //       "authors": "Update by unit testing"
  //     });
  //   expect(res.statusCode).toEqual(200);
  //   expect(res.body).toHaveProperty('post');
  //   expect(res.body.post).toHaveProperty('title', 'updated title');
  // });

// });


// describe('Post Book endpoints', () => {
//   it('should create a new Book', () => {
//     const res = await request(app)
//       .post('/api/books')
//       .send({
//         id: "622771b8f274c05e1b8a7fe2", //id example, not autogenerated
//         name: "Harry Potter And The Philosopher`s Stone",
//         authors: "J.K Rowling",
//         publisher: "Bloomsbury Childrens Books",
//         yearOfPublication: 1997,
//         summary: "Harry Potter and the Philosopher's Stone is an enthralling start to Harry's journey toward coming to terms with his past and facing his future."
//       })
//     expect(res.statusCode).toEqual(201)
//     expect(res.body).toHaveProperty('post')
//   })
// })