const request = require('supertest')
const app = require('../../server')
const uniqueId = 123456;
const uniqueId2 = 123432;

describe('Post Endpoints', () => {

  //test1
  // it('should create a new book', async () => {
  //   const res = await request(app)
  //     .post('/api/books')
  //     .send({
  //       id: `${uniqueId}`, //id example, not autogenerated
  //       name: "Harry Potter And The Philosopher`s Stone",
  //       authors: "J.K Rowling",
  //       publisher: "Bloomsbury Childrens Books",
  //       yearOfPublication: 1997,
  //       summary: "Harry Potter and the Philosopher's Stone is an enthralling start to Harry's journey toward coming to terms with his past and facing his future."
  //     });
  //   expect(res.statusCode).toEqual(200);
  //   expect(res.request.method).toEqual('POST');
  // });

  //test2
  // it('should create a new book', async () => {
  //   const res = await request(app)
  //     .post('/api/books')
  //     .send({
  //       id: `${uniqueId2}`, //id example, not autogenerated
  //       name: "It: A Novel",
  //       authors: "Stephen King",
  //       publisher: "Suma",
  //       yearOfPublication: 2014,
  //       summary: "Welcome to Derry, Maine. Its a small city, a place as hauntingly familiar as your own hometown. Only in Derry the haunting is real.",
  //     });
  //   expect(res.statusCode).toEqual(200);
  //   expect(res.request.method).toEqual('POST');
  // });

  //test3
  it('should delete a book', async () => {
    const res = await request(app)
    .delete('/api/books/id='+`${uniqueId}`)
    .send({
      id: `${uniqueId}`, //id example, not autogenerated
    });
    expect(res.statusCode).toEqual(200); //OK book deleted using ID
    expect(res.request.method).toEqual('DELETE');
  });



  
});
